/** Columns required for meets list cards, tabs, and join/leave state (no route geometry). */
export const MEET_LIST_SELECT = [
  "id",
  "host_id",
  "co_host_id",
  "name",
  "date",
  "time",
  "meet_point",
  "meet_point_lat",
  "meet_point_lng",
  "destination",
  "destination_lat",
  "destination_lng",
  "city",
  "type",
  "privacy",
  "visibility",
  "priority_access",
  "priority_open_at",
  "distance",
  "duration",
  "meet_duration_minutes",
  "description",
  "cover",
  "tracking_status",
  "started_at",
  "ended_at",
  "status",
  "created_at",
].join(", ");
